// <auto-generated />
using System;
using E_Dnevnik_API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace E_Dnevnik_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("E_Dnevnik_API.Database.Models.GradeBaseline", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("SchoolYear")
                        .HasColumnType("text");

                    b.Property<decimal>("BaselineAverage")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Email", "SchoolYear");

                    b.ToTable("GradeBaselines");
                });

            modelBuilder.Entity("E_Dnevnik_API.Database.Models.GradeSnapshot", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("SubjectId")
                        .HasColumnType("text");

                    b.Property<decimal>("LastKnownAverage")
                        .HasColumnType("numeric");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Email", "SubjectId");

                    b.ToTable("GradeSnapshots");
                });

            modelBuilder.Entity("E_Dnevnik_API.Database.Models.LeaderboardEntry", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CombinedScore")
                        .HasColumnType("numeric");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<decimal>("GradeDeltaScore")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("LastScoreUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("OptedInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SchoolId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("StreakScore")
                        .HasColumnType("numeric");

                    b.HasKey("Email");

                    b.ToTable("LeaderboardEntries");
                });

            modelBuilder.Entity("E_Dnevnik_API.Database.Models.MonitoredSubject", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("SubjectId")
                        .HasColumnType("text");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Email", "SubjectId");

                    b.ToTable("MonitoredSubjects");
                });

            modelBuilder.Entity("E_Dnevnik_API.Database.Models.PomodoroSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<int>("SessionsCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email", "SessionDate")
                        .IsUnique();

                    b.ToTable("PomodoroSessions");
                });

            modelBuilder.Entity("E_Dnevnik_API.Database.Models.StudentCache", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AbsencesCachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AbsencesData")
                        .HasColumnType("text");

                    b.Property<string>("ActiveToken")
                        .HasColumnType("text");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FcmTokenUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GradesCachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GradesData")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GradesDifferentCachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GradesDifferentData")
                        .HasColumnType("text");

                    b.Property<bool>("IsOdlikasPlus")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastForceRefreshAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OdlikasPlusSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProfileCachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfileData")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduleCachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScheduleData")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SpecificSubjectGradesCachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpecificSubjectGradesJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TestsCachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TestsData")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenStoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Email");

                    b.ToTable("StudentCache");
                });

            modelBuilder.Entity("E_Dnevnik_API.Database.Models.TaskSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TasksJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TaskSets");
                });
#pragma warning restore 612, 618
        }
    }
}
